- name: install nginx and start, enable the nginx 
  hosts: web
  become: true 
  tasks:  
    - name: install nginx 
      ansible.builtin.dnf:
        name: nginx
        state: latest  
    - name: start and enable the service 
      ansible.builtin.service:
        name: nginx
        state: started 
        enabled: yes 
