- name : diff task and global level variables 
  hosts: web
  vars_prompt:
   - name: please enter the course
     prompt: course_1
     private: no 
   - name: please enter the duration 
     prompt: duration_1
     private: no 
   - name: pleasse enter the trainner 
     prompt: trainner_1
     private: yes  
  vars:
    - course: DevOps with AWS 
    - trainner: kedarnath 
    - duration: 120 days 
  tasks:
    - name: task level variables
      vars:
        - course: ansible 
        - duration: 7 days 
        - trainner: kishore 
      ansible.builtin.debug:
        msg: "hello current running course is :{{course}}, duration may takes: {{duration}} & trainner is {{trainner}}"
    
    - name: play level variables
      ansible.builtin.debug:
        msg:  "hello current running course is :{{course}}, duration may takes: {{duration}} & trainner is {{trainner}}"

    - name: vars from prompt 
      ansible.builtin.debug:
        msg:  "hello current running course is :{{course_1}}, duration may takes: {{duration_1}} & trainner is {{trainner_1}}"
