- name : variable from file 
  hosts: localhost
  vars_files:
    - 
  tasks: 
    - name: printing from the files 
      ansible.builtin.debug:
        msg: " Student_name is :{{}}, class is :{{}} & fav subject is :{{fav_subject}} "