- name : variables from file 
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks: 
    - name: printing from the files 
      ansible.builtin.debug:
        msg: " Student_name is :{{Student_name}}, class is :{{class}} & fav subject is :{{fav_subject}} "