- name : check an user is existed or not if not create an user  
  hosts: localhost
  become: true 
  tasks:
    - name: check an user is existed or not  
      ansible.builtin.command: id expense 
      register: user_expense 
      ignore_errors: True 

    - name: user_expense output 
      ansible.builtin.debug:
        msg: "{{user_expense}}"

    - name: create an user if not existed
      ansible.builtin.command: useradd expense 
      when: user_expense.re = 1 | int 