- name : conditions 
  hosts: localhost
  tasks:
    - name: check an user is existed or not  
      ansible.builtin.command: id expense 
      registor: user_expense 
      ignore_errors: True 

    - name: user_expense output 
      ansible.builtin.debug:
        msg: "{{user_expense}}"