- name : conditions 
  hosts: localhost
  tasks:
    - name: check an user is existed or not  
      ansible.builtin.command: id expense 
      ignore_error: yes 

    - name: print some thing
      ansible.builtin.debug:
        msg: "hello " 