- name : print the default values 
  hosts: localhost
  tasks:
    - name: default values are 
      ansible.builtin.debug:
        msg: "we are learning the {{course | default ('ansible') }}"

- name : convert in to uppper case 
  hosts: localhost
  vars:
    wishes: "hello good morning "
  tasks:
    - name: convet in to upper 
      ansible.builtin.debug:
        msg: "{{ wishes | upper }}"
  
- name: convert upper to lower 
  hosts: localhost
  vars:
    wishes: " HELLO GOOD MORNING "
  tasks:
    - name: convert to lower 
      ansible.builtin.debug:
        msg: "{{ wishes | lower }}"
- name : remove duplicates in list 
  hosts: localhost
  vars:
    marks: [ 15, 15, 65, 65, 68]
  tasks: 
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{ marks | unique }}"

- name : find max and min
  hosts: localhost
  vars: 
    ages: [10, 45, 65, 25, 65, 88]
  tasks:
    - name: print min and max values
      ansible.builtin.debug:
        msg: "min value is {{ ages | min }}, & max value is {{ ages | max }}"


- name : converet dict to list 
  hosts: localhost
  vars: 
    my_dict:
      docker: 2yars 
      k8s: 1 year 
      jenkins: 2 yars 
  tasks: 
    - name: before "convertion
      ansible.builtin.debug:
        msg: "before convertiong {{my_dict}}"

        
    - name: convert the dict to items 
      ansible.builtin.debug:
        msg: "convertion of dict to iteams {{my_dict | dict2items }}"

- name : convert list to dictonary 
  hosts: localhost
  vars:
    tools: 
      - ansible 
      - git 
      - docker 
      - k8s 
      - shell
  tasks:
    - name: convert list to dictonary 
      ansible.builtin.dnf:
        msg: "list to dictonary is {{ tools | item2dict }}"


  