- name : demo on loop 
  hosts: localhost
  tasks: 
    - name: print the list 
      ansible.builtin.debug:
        msg: "tools are {{ item }}"
      loop: 
       - linux 
       - ansible 
       - shell 
