- name : install some packages 
  hosts: localhost
  become: yes 
  tasks:
    - name: install the list of packages 
      ansible.builtin.dnf:
         name: "{{ item }}"
         state: present
      loop:
        - mysql 
        - git 
        - gcc  
    
        