- name: demo on dict 
  hosts: localhost
  vars:
    - my_dict:  
        - git: 'latest'
        - ansible: 'latest'
        - gcc: 'absent'
  tasks:
    - name: print the dict 
      ansible.builtin.debug:
        msg: "{{my_dict}}"
    