- name: demo on dict 
  hosts: localhost
  tasks:
    - name: print the dict
      ansible.builtin.debug:
        msg:  "hello tools are {{my_dict.key}} & state is {{my_dict.value}}"
      my_dict:  
        - git: 'latest'
        - ansible: 'latest'
        - gcc: 'absent'